-- TP/SL订单表
CREATE TABLE IF NOT EXISTS t_tp_sl_order (
    id                  BIGINT PRIMARY KEY AUTO_INCREMENT,
    order_id            BIGINT NOT NULL COMMENT 'TP/SL订单ID',
    user_id             BIGINT NOT NULL COMMENT '用户ID',
    symbol              VARCHAR(32) NOT NULL COMMENT '交易对',
    client_order_id     VARCHAR(64) COMMENT '客户端订单ID',
    position_id         BIGINT COMMENT '关联持仓ID',
    parent_order_id     BIGINT COMMENT '关联父订单ID',
    order_type          VARCHAR(16) NOT NULL COMMENT '类型: TP/SL/TRAILING',
    trigger_type        VARCHAR(16) NOT NULL DEFAULT 'MARK' COMMENT '触发类型',
    trigger_direction   VARCHAR(16) COMMENT '触发方向',
    trigger_price       BIGINT NOT NULL COMMENT '触发价格',
    trigger_side        VARCHAR(8) NOT NULL COMMENT '方向: LONG/SHORT',
    close_side          TINYINT COMMENT '平仓方向',
    exec_type           VARCHAR(16) NOT NULL COMMENT '执行类型',
    exec_price          BIGINT COMMENT '执行限价',
    quantity            BIGINT NOT NULL COMMENT '平仓数量',
    trailing_offset     BIGINT COMMENT '回调偏移量',
    trailing_percent    BIGINT COMMENT '回调比例',
    trailing_callback_rate      BIGINT COMMENT '回调比例',
    trailing_callback_distance  BIGINT COMMENT '回调距离',
    trailing_active_price       BIGINT COMMENT '激活价格',
    highest_price       BIGINT COMMENT '最高/低价',
    status              VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态',
    trigger_time        BIGINT COMMENT '触发时间',
    triggered_time      BIGINT COMMENT '触发时间戳',
    triggered_price     BIGINT COMMENT '触发价格',
    exec_order_id       BIGINT COMMENT '平仓订单ID',
    close_order_id      BIGINT COMMENT '平仓订单ID',
    exec_result         VARCHAR(16) COMMENT '执行结果',
    expire_time         BIGINT COMMENT '过期时间',
    create_time         BIGINT NOT NULL COMMENT '创建时间戳',
    update_time         BIGINT NOT NULL COMMENT '更新时间戳',
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_order_id (order_id),
    KEY idx_user_id (user_id),
    KEY idx_symbol (symbol),
    KEY idx_position_id (position_id),
    KEY idx_status (status),
    KEY idx_symbol_status (symbol, status),
    KEY idx_user_client_order (user_id, client_order_id),
    KEY idx_symbol_status_trigger (symbol, status, trigger_price)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='止盈止损订单表';

-- TP/SL执行日志表
CREATE TABLE IF NOT EXISTS t_tp_sl_exec_log (
    id                  BIGINT PRIMARY KEY AUTO_INCREMENT,
    tp_sl_order_id      BIGINT NOT NULL COMMENT 'TP/SL订单ID',
    user_id             BIGINT NOT NULL COMMENT '用户ID',
    symbol              VARCHAR(32) NOT NULL COMMENT '交易对',
    trigger_price       BIGINT NOT NULL COMMENT '触发价格',
    mark_price          BIGINT NOT NULL COMMENT '标记价格',
    exec_type           VARCHAR(16) NOT NULL COMMENT '执行类型',
    quantity            BIGINT NOT NULL COMMENT '执行数量',
    exec_order_id       BIGINT COMMENT '平仓订单ID',
    exec_result         VARCHAR(16) COMMENT '执行结果',
    error_msg           VARCHAR(512) COMMENT '错误信息',
    create_time         BIGINT NOT NULL COMMENT '创建时间戳',
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_tp_sl_order_id (tp_sl_order_id),
    KEY idx_user_id (user_id),
    KEY idx_created_at (created_at),
    KEY idx_exec_result (exec_result)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='TP/SL执行日志表';
