// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order_command.proto
// Protobuf Java Version: 4.33.4

package com.exchange.common.proto;

@com.google.protobuf.Generated
public final class OrderProto extends com.google.protobuf.GeneratedFile {
  private OrderProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "OrderProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.exchange.common.proto.OrderCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 订单ID
     * </pre>
     *
     * <code>int64 order_id = 1;</code>
     * @return The orderId.
     */
    long getOrderId();

    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 user_id = 2;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <pre>
     * 交易对
     * </pre>
     *
     * <code>string symbol = 3;</code>
     * @return The symbol.
     */
    java.lang.String getSymbol();
    /**
     * <pre>
     * 交易对
     * </pre>
     *
     * <code>string symbol = 3;</code>
     * @return The bytes for symbol.
     */
    com.google.protobuf.ByteString
        getSymbolBytes();

    /**
     * <pre>
     * 买卖方向（BUY, SELL）
     * </pre>
     *
     * <code>string side = 4;</code>
     * @return The side.
     */
    java.lang.String getSide();
    /**
     * <pre>
     * 买卖方向（BUY, SELL）
     * </pre>
     *
     * <code>string side = 4;</code>
     * @return The bytes for side.
     */
    com.google.protobuf.ByteString
        getSideBytes();

    /**
     * <pre>
     * 订单类型（LIMIT, MARKET）
     * </pre>
     *
     * <code>string order_type = 5;</code>
     * @return The orderType.
     */
    java.lang.String getOrderType();
    /**
     * <pre>
     * 订单类型（LIMIT, MARKET）
     * </pre>
     *
     * <code>string order_type = 5;</code>
     * @return The bytes for orderType.
     */
    com.google.protobuf.ByteString
        getOrderTypeBytes();

    /**
     * <pre>
     * 价格（字符串，避免精度问题）
     * </pre>
     *
     * <code>string price = 6;</code>
     * @return The price.
     */
    java.lang.String getPrice();
    /**
     * <pre>
     * 价格（字符串，避免精度问题）
     * </pre>
     *
     * <code>string price = 6;</code>
     * @return The bytes for price.
     */
    com.google.protobuf.ByteString
        getPriceBytes();

    /**
     * <pre>
     * 数量（字符串，避免精度问题）
     * </pre>
     *
     * <code>string quantity = 7;</code>
     * @return The quantity.
     */
    java.lang.String getQuantity();
    /**
     * <pre>
     * 数量（字符串，避免精度问题）
     * </pre>
     *
     * <code>string quantity = 7;</code>
     * @return The bytes for quantity.
     */
    com.google.protobuf.ByteString
        getQuantityBytes();

    /**
     * <pre>
     * 事件类型（ORDER_SUBMIT, ORDER_CANCEL, ORDER_FORCE_CANCEL）
     * </pre>
     *
     * <code>string event_type = 8;</code>
     * @return The eventType.
     */
    java.lang.String getEventType();
    /**
     * <pre>
     * 事件类型（ORDER_SUBMIT, ORDER_CANCEL, ORDER_FORCE_CANCEL）
     * </pre>
     *
     * <code>string event_type = 8;</code>
     * @return The bytes for eventType.
     */
    com.google.protobuf.ByteString
        getEventTypeBytes();

    /**
     * <pre>
     * 时间戳（毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 9;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * 客户端订单ID（可选）
     * </pre>
     *
     * <code>string client_order_id = 10;</code>
     * @return The clientOrderId.
     */
    java.lang.String getClientOrderId();
    /**
     * <pre>
     * 客户端订单ID（可选）
     * </pre>
     *
     * <code>string client_order_id = 10;</code>
     * @return The bytes for clientOrderId.
     */
    com.google.protobuf.ByteString
        getClientOrderIdBytes();
  }
  /**
   * <pre>
   * *
   * 订单命令消息
   * 用于 OMS → Match Engine 通信
   * </pre>
   *
   * Protobuf type {@code com.exchange.common.proto.OrderCommand}
   */
  public static final class OrderCommand extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.exchange.common.proto.OrderCommand)
      OrderCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 4,
        /* suffix= */ "",
        "OrderCommand");
    }
    // Use OrderCommand.newBuilder() to construct.
    private OrderCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private OrderCommand() {
      symbol_ = "";
      side_ = "";
      orderType_ = "";
      price_ = "";
      quantity_ = "";
      eventType_ = "";
      clientOrderId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.exchange.common.proto.OrderProto.internal_static_com_exchange_common_proto_OrderCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.exchange.common.proto.OrderProto.internal_static_com_exchange_common_proto_OrderCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.exchange.common.proto.OrderProto.OrderCommand.class, com.exchange.common.proto.OrderProto.OrderCommand.Builder.class);
    }

    public static final int ORDER_ID_FIELD_NUMBER = 1;
    private long orderId_ = 0L;
    /**
     * <pre>
     * 订单ID
     * </pre>
     *
     * <code>int64 order_id = 1;</code>
     * @return The orderId.
     */
    @java.lang.Override
    public long getOrderId() {
      return orderId_;
    }

    public static final int USER_ID_FIELD_NUMBER = 2;
    private long userId_ = 0L;
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 user_id = 2;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int SYMBOL_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object symbol_ = "";
    /**
     * <pre>
     * 交易对
     * </pre>
     *
     * <code>string symbol = 3;</code>
     * @return The symbol.
     */
    @java.lang.Override
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 交易对
     * </pre>
     *
     * <code>string symbol = 3;</code>
     * @return The bytes for symbol.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIDE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object side_ = "";
    /**
     * <pre>
     * 买卖方向（BUY, SELL）
     * </pre>
     *
     * <code>string side = 4;</code>
     * @return The side.
     */
    @java.lang.Override
    public java.lang.String getSide() {
      java.lang.Object ref = side_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        side_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 买卖方向（BUY, SELL）
     * </pre>
     *
     * <code>string side = 4;</code>
     * @return The bytes for side.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSideBytes() {
      java.lang.Object ref = side_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        side_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDER_TYPE_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object orderType_ = "";
    /**
     * <pre>
     * 订单类型（LIMIT, MARKET）
     * </pre>
     *
     * <code>string order_type = 5;</code>
     * @return The orderType.
     */
    @java.lang.Override
    public java.lang.String getOrderType() {
      java.lang.Object ref = orderType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 订单类型（LIMIT, MARKET）
     * </pre>
     *
     * <code>string order_type = 5;</code>
     * @return The bytes for orderType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOrderTypeBytes() {
      java.lang.Object ref = orderType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object price_ = "";
    /**
     * <pre>
     * 价格（字符串，避免精度问题）
     * </pre>
     *
     * <code>string price = 6;</code>
     * @return The price.
     */
    @java.lang.Override
    public java.lang.String getPrice() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        price_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 价格（字符串，避免精度问题）
     * </pre>
     *
     * <code>string price = 6;</code>
     * @return The bytes for price.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object quantity_ = "";
    /**
     * <pre>
     * 数量（字符串，避免精度问题）
     * </pre>
     *
     * <code>string quantity = 7;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public java.lang.String getQuantity() {
      java.lang.Object ref = quantity_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quantity_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 数量（字符串，避免精度问题）
     * </pre>
     *
     * <code>string quantity = 7;</code>
     * @return The bytes for quantity.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQuantityBytes() {
      java.lang.Object ref = quantity_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quantity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_TYPE_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object eventType_ = "";
    /**
     * <pre>
     * 事件类型（ORDER_SUBMIT, ORDER_CANCEL, ORDER_FORCE_CANCEL）
     * </pre>
     *
     * <code>string event_type = 8;</code>
     * @return The eventType.
     */
    @java.lang.Override
    public java.lang.String getEventType() {
      java.lang.Object ref = eventType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 事件类型（ORDER_SUBMIT, ORDER_CANCEL, ORDER_FORCE_CANCEL）
     * </pre>
     *
     * <code>string event_type = 8;</code>
     * @return The bytes for eventType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      java.lang.Object ref = eventType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 9;
    private long timestamp_ = 0L;
    /**
     * <pre>
     * 时间戳（毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 9;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int CLIENT_ORDER_ID_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object clientOrderId_ = "";
    /**
     * <pre>
     * 客户端订单ID（可选）
     * </pre>
     *
     * <code>string client_order_id = 10;</code>
     * @return The clientOrderId.
     */
    @java.lang.Override
    public java.lang.String getClientOrderId() {
      java.lang.Object ref = clientOrderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientOrderId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 客户端订单ID（可选）
     * </pre>
     *
     * <code>string client_order_id = 10;</code>
     * @return The bytes for clientOrderId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientOrderIdBytes() {
      java.lang.Object ref = clientOrderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientOrderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (orderId_ != 0L) {
        output.writeInt64(1, orderId_);
      }
      if (userId_ != 0L) {
        output.writeInt64(2, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, symbol_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(side_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, side_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(orderType_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, orderType_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(price_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, price_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quantity_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, quantity_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, eventType_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(9, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientOrderId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, clientOrderId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (orderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, orderId_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, symbol_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(side_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, side_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(orderType_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, orderType_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(price_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, price_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quantity_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, quantity_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, eventType_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientOrderId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10, clientOrderId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.exchange.common.proto.OrderProto.OrderCommand)) {
        return super.equals(obj);
      }
      com.exchange.common.proto.OrderProto.OrderCommand other = (com.exchange.common.proto.OrderProto.OrderCommand) obj;

      if (getOrderId()
          != other.getOrderId()) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getSymbol()
          .equals(other.getSymbol())) return false;
      if (!getSide()
          .equals(other.getSide())) return false;
      if (!getOrderType()
          .equals(other.getOrderType())) return false;
      if (!getPrice()
          .equals(other.getPrice())) return false;
      if (!getQuantity()
          .equals(other.getQuantity())) return false;
      if (!getEventType()
          .equals(other.getEventType())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getClientOrderId()
          .equals(other.getClientOrderId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ORDER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOrderId());
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol().hashCode();
      hash = (37 * hash) + SIDE_FIELD_NUMBER;
      hash = (53 * hash) + getSide().hashCode();
      hash = (37 * hash) + ORDER_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getOrderType().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice().hashCode();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity().hashCode();
      hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getEventType().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + CLIENT_ORDER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getClientOrderId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.exchange.common.proto.OrderProto.OrderCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.exchange.common.proto.OrderProto.OrderCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.exchange.common.proto.OrderProto.OrderCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.exchange.common.proto.OrderProto.OrderCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * *
     * 订单命令消息
     * 用于 OMS → Match Engine 通信
     * </pre>
     *
     * Protobuf type {@code com.exchange.common.proto.OrderCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.exchange.common.proto.OrderCommand)
        com.exchange.common.proto.OrderProto.OrderCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.exchange.common.proto.OrderProto.internal_static_com_exchange_common_proto_OrderCommand_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.exchange.common.proto.OrderProto.internal_static_com_exchange_common_proto_OrderCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.exchange.common.proto.OrderProto.OrderCommand.class, com.exchange.common.proto.OrderProto.OrderCommand.Builder.class);
      }

      // Construct using com.exchange.common.proto.OrderProto.OrderCommand.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        orderId_ = 0L;
        userId_ = 0L;
        symbol_ = "";
        side_ = "";
        orderType_ = "";
        price_ = "";
        quantity_ = "";
        eventType_ = "";
        timestamp_ = 0L;
        clientOrderId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.exchange.common.proto.OrderProto.internal_static_com_exchange_common_proto_OrderCommand_descriptor;
      }

      @java.lang.Override
      public com.exchange.common.proto.OrderProto.OrderCommand getDefaultInstanceForType() {
        return com.exchange.common.proto.OrderProto.OrderCommand.getDefaultInstance();
      }

      @java.lang.Override
      public com.exchange.common.proto.OrderProto.OrderCommand build() {
        com.exchange.common.proto.OrderProto.OrderCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.exchange.common.proto.OrderProto.OrderCommand buildPartial() {
        com.exchange.common.proto.OrderProto.OrderCommand result = new com.exchange.common.proto.OrderProto.OrderCommand(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.exchange.common.proto.OrderProto.OrderCommand result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.orderId_ = orderId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.symbol_ = symbol_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.side_ = side_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.orderType_ = orderType_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.price_ = price_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.quantity_ = quantity_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.eventType_ = eventType_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.clientOrderId_ = clientOrderId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.exchange.common.proto.OrderProto.OrderCommand) {
          return mergeFrom((com.exchange.common.proto.OrderProto.OrderCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.exchange.common.proto.OrderProto.OrderCommand other) {
        if (other == com.exchange.common.proto.OrderProto.OrderCommand.getDefaultInstance()) return this;
        if (other.getOrderId() != 0L) {
          setOrderId(other.getOrderId());
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getSymbol().isEmpty()) {
          symbol_ = other.symbol_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getSide().isEmpty()) {
          side_ = other.side_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getOrderType().isEmpty()) {
          orderType_ = other.orderType_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getPrice().isEmpty()) {
          price_ = other.price_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getQuantity().isEmpty()) {
          quantity_ = other.quantity_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (!other.getEventType().isEmpty()) {
          eventType_ = other.eventType_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getClientOrderId().isEmpty()) {
          clientOrderId_ = other.clientOrderId_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                orderId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                userId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                symbol_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                side_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                orderType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                price_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                quantity_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                eventType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 72: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 82: {
                clientOrderId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long orderId_ ;
      /**
       * <pre>
       * 订单ID
       * </pre>
       *
       * <code>int64 order_id = 1;</code>
       * @return The orderId.
       */
      @java.lang.Override
      public long getOrderId() {
        return orderId_;
      }
      /**
       * <pre>
       * 订单ID
       * </pre>
       *
       * <code>int64 order_id = 1;</code>
       * @param value The orderId to set.
       * @return This builder for chaining.
       */
      public Builder setOrderId(long value) {

        orderId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 订单ID
       * </pre>
       *
       * <code>int64 order_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        orderId_ = 0L;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <pre>
       * 用户ID
       * </pre>
       *
       * <code>int64 user_id = 2;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <pre>
       * 用户ID
       * </pre>
       *
       * <code>int64 user_id = 2;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {

        userId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户ID
       * </pre>
       *
       * <code>int64 user_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object symbol_ = "";
      /**
       * <pre>
       * 交易对
       * </pre>
       *
       * <code>string symbol = 3;</code>
       * @return The symbol.
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 交易对
       * </pre>
       *
       * <code>string symbol = 3;</code>
       * @return The bytes for symbol.
       */
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 交易对
       * </pre>
       *
       * <code>string symbol = 3;</code>
       * @param value The symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        symbol_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交易对
       * </pre>
       *
       * <code>string symbol = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSymbol() {
        symbol_ = getDefaultInstance().getSymbol();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交易对
       * </pre>
       *
       * <code>string symbol = 3;</code>
       * @param value The bytes for symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        symbol_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object side_ = "";
      /**
       * <pre>
       * 买卖方向（BUY, SELL）
       * </pre>
       *
       * <code>string side = 4;</code>
       * @return The side.
       */
      public java.lang.String getSide() {
        java.lang.Object ref = side_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          side_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 买卖方向（BUY, SELL）
       * </pre>
       *
       * <code>string side = 4;</code>
       * @return The bytes for side.
       */
      public com.google.protobuf.ByteString
          getSideBytes() {
        java.lang.Object ref = side_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          side_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 买卖方向（BUY, SELL）
       * </pre>
       *
       * <code>string side = 4;</code>
       * @param value The side to set.
       * @return This builder for chaining.
       */
      public Builder setSide(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        side_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 买卖方向（BUY, SELL）
       * </pre>
       *
       * <code>string side = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSide() {
        side_ = getDefaultInstance().getSide();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 买卖方向（BUY, SELL）
       * </pre>
       *
       * <code>string side = 4;</code>
       * @param value The bytes for side to set.
       * @return This builder for chaining.
       */
      public Builder setSideBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        side_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object orderType_ = "";
      /**
       * <pre>
       * 订单类型（LIMIT, MARKET）
       * </pre>
       *
       * <code>string order_type = 5;</code>
       * @return The orderType.
       */
      public java.lang.String getOrderType() {
        java.lang.Object ref = orderType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 订单类型（LIMIT, MARKET）
       * </pre>
       *
       * <code>string order_type = 5;</code>
       * @return The bytes for orderType.
       */
      public com.google.protobuf.ByteString
          getOrderTypeBytes() {
        java.lang.Object ref = orderType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 订单类型（LIMIT, MARKET）
       * </pre>
       *
       * <code>string order_type = 5;</code>
       * @param value The orderType to set.
       * @return This builder for chaining.
       */
      public Builder setOrderType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        orderType_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 订单类型（LIMIT, MARKET）
       * </pre>
       *
       * <code>string order_type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderType() {
        orderType_ = getDefaultInstance().getOrderType();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 订单类型（LIMIT, MARKET）
       * </pre>
       *
       * <code>string order_type = 5;</code>
       * @param value The bytes for orderType to set.
       * @return This builder for chaining.
       */
      public Builder setOrderTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        orderType_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object price_ = "";
      /**
       * <pre>
       * 价格（字符串，避免精度问题）
       * </pre>
       *
       * <code>string price = 6;</code>
       * @return The price.
       */
      public java.lang.String getPrice() {
        java.lang.Object ref = price_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          price_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 价格（字符串，避免精度问题）
       * </pre>
       *
       * <code>string price = 6;</code>
       * @return The bytes for price.
       */
      public com.google.protobuf.ByteString
          getPriceBytes() {
        java.lang.Object ref = price_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          price_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 价格（字符串，避免精度问题）
       * </pre>
       *
       * <code>string price = 6;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        price_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 价格（字符串，避免精度问题）
       * </pre>
       *
       * <code>string price = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        price_ = getDefaultInstance().getPrice();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 价格（字符串，避免精度问题）
       * </pre>
       *
       * <code>string price = 6;</code>
       * @param value The bytes for price to set.
       * @return This builder for chaining.
       */
      public Builder setPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        price_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object quantity_ = "";
      /**
       * <pre>
       * 数量（字符串，避免精度问题）
       * </pre>
       *
       * <code>string quantity = 7;</code>
       * @return The quantity.
       */
      public java.lang.String getQuantity() {
        java.lang.Object ref = quantity_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          quantity_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 数量（字符串，避免精度问题）
       * </pre>
       *
       * <code>string quantity = 7;</code>
       * @return The bytes for quantity.
       */
      public com.google.protobuf.ByteString
          getQuantityBytes() {
        java.lang.Object ref = quantity_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          quantity_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 数量（字符串，避免精度问题）
       * </pre>
       *
       * <code>string quantity = 7;</code>
       * @param value The quantity to set.
       * @return This builder for chaining.
       */
      public Builder setQuantity(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        quantity_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数量（字符串，避免精度问题）
       * </pre>
       *
       * <code>string quantity = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantity() {
        quantity_ = getDefaultInstance().getQuantity();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数量（字符串，避免精度问题）
       * </pre>
       *
       * <code>string quantity = 7;</code>
       * @param value The bytes for quantity to set.
       * @return This builder for chaining.
       */
      public Builder setQuantityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        quantity_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.lang.Object eventType_ = "";
      /**
       * <pre>
       * 事件类型（ORDER_SUBMIT, ORDER_CANCEL, ORDER_FORCE_CANCEL）
       * </pre>
       *
       * <code>string event_type = 8;</code>
       * @return The eventType.
       */
      public java.lang.String getEventType() {
        java.lang.Object ref = eventType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 事件类型（ORDER_SUBMIT, ORDER_CANCEL, ORDER_FORCE_CANCEL）
       * </pre>
       *
       * <code>string event_type = 8;</code>
       * @return The bytes for eventType.
       */
      public com.google.protobuf.ByteString
          getEventTypeBytes() {
        java.lang.Object ref = eventType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 事件类型（ORDER_SUBMIT, ORDER_CANCEL, ORDER_FORCE_CANCEL）
       * </pre>
       *
       * <code>string event_type = 8;</code>
       * @param value The eventType to set.
       * @return This builder for chaining.
       */
      public Builder setEventType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        eventType_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 事件类型（ORDER_SUBMIT, ORDER_CANCEL, ORDER_FORCE_CANCEL）
       * </pre>
       *
       * <code>string event_type = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventType() {
        eventType_ = getDefaultInstance().getEventType();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 事件类型（ORDER_SUBMIT, ORDER_CANCEL, ORDER_FORCE_CANCEL）
       * </pre>
       *
       * <code>string event_type = 8;</code>
       * @param value The bytes for eventType to set.
       * @return This builder for chaining.
       */
      public Builder setEventTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        eventType_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * 时间戳（毫秒）
       * </pre>
       *
       * <code>int64 timestamp = 9;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * 时间戳（毫秒）
       * </pre>
       *
       * <code>int64 timestamp = 9;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时间戳（毫秒）
       * </pre>
       *
       * <code>int64 timestamp = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000100);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object clientOrderId_ = "";
      /**
       * <pre>
       * 客户端订单ID（可选）
       * </pre>
       *
       * <code>string client_order_id = 10;</code>
       * @return The clientOrderId.
       */
      public java.lang.String getClientOrderId() {
        java.lang.Object ref = clientOrderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientOrderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 客户端订单ID（可选）
       * </pre>
       *
       * <code>string client_order_id = 10;</code>
       * @return The bytes for clientOrderId.
       */
      public com.google.protobuf.ByteString
          getClientOrderIdBytes() {
        java.lang.Object ref = clientOrderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientOrderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 客户端订单ID（可选）
       * </pre>
       *
       * <code>string client_order_id = 10;</code>
       * @param value The clientOrderId to set.
       * @return This builder for chaining.
       */
      public Builder setClientOrderId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        clientOrderId_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端订单ID（可选）
       * </pre>
       *
       * <code>string client_order_id = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientOrderId() {
        clientOrderId_ = getDefaultInstance().getClientOrderId();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端订单ID（可选）
       * </pre>
       *
       * <code>string client_order_id = 10;</code>
       * @param value The bytes for clientOrderId to set.
       * @return This builder for chaining.
       */
      public Builder setClientOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        clientOrderId_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.exchange.common.proto.OrderCommand)
    }

    // @@protoc_insertion_point(class_scope:com.exchange.common.proto.OrderCommand)
    private static final com.exchange.common.proto.OrderProto.OrderCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.exchange.common.proto.OrderProto.OrderCommand();
    }

    public static com.exchange.common.proto.OrderProto.OrderCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderCommand>
        PARSER = new com.google.protobuf.AbstractParser<OrderCommand>() {
      @java.lang.Override
      public OrderCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OrderCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderCommand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.exchange.common.proto.OrderProto.OrderCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrderCommandBatchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.exchange.common.proto.OrderCommandBatch)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 批量订单
     * </pre>
     *
     * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
     */
    java.util.List<com.exchange.common.proto.OrderProto.OrderCommand> 
        getCommandsList();
    /**
     * <pre>
     * 批量订单
     * </pre>
     *
     * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
     */
    com.exchange.common.proto.OrderProto.OrderCommand getCommands(int index);
    /**
     * <pre>
     * 批量订单
     * </pre>
     *
     * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
     */
    int getCommandsCount();
    /**
     * <pre>
     * 批量订单
     * </pre>
     *
     * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
     */
    java.util.List<? extends com.exchange.common.proto.OrderProto.OrderCommandOrBuilder> 
        getCommandsOrBuilderList();
    /**
     * <pre>
     * 批量订单
     * </pre>
     *
     * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
     */
    com.exchange.common.proto.OrderProto.OrderCommandOrBuilder getCommandsOrBuilder(
        int index);

    /**
     * <pre>
     * 批次ID
     * </pre>
     *
     * <code>string batch_id = 2;</code>
     * @return The batchId.
     */
    java.lang.String getBatchId();
    /**
     * <pre>
     * 批次ID
     * </pre>
     *
     * <code>string batch_id = 2;</code>
     * @return The bytes for batchId.
     */
    com.google.protobuf.ByteString
        getBatchIdBytes();

    /**
     * <pre>
     * 批次时间戳
     * </pre>
     *
     * <code>int64 batch_timestamp = 3;</code>
     * @return The batchTimestamp.
     */
    long getBatchTimestamp();
  }
  /**
   * <pre>
   * *
   * 批量订单命令（预留，用于批量下单优化）
   * </pre>
   *
   * Protobuf type {@code com.exchange.common.proto.OrderCommandBatch}
   */
  public static final class OrderCommandBatch extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.exchange.common.proto.OrderCommandBatch)
      OrderCommandBatchOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 4,
        /* suffix= */ "",
        "OrderCommandBatch");
    }
    // Use OrderCommandBatch.newBuilder() to construct.
    private OrderCommandBatch(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private OrderCommandBatch() {
      commands_ = java.util.Collections.emptyList();
      batchId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.exchange.common.proto.OrderProto.internal_static_com_exchange_common_proto_OrderCommandBatch_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.exchange.common.proto.OrderProto.internal_static_com_exchange_common_proto_OrderCommandBatch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.exchange.common.proto.OrderProto.OrderCommandBatch.class, com.exchange.common.proto.OrderProto.OrderCommandBatch.Builder.class);
    }

    public static final int COMMANDS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.exchange.common.proto.OrderProto.OrderCommand> commands_;
    /**
     * <pre>
     * 批量订单
     * </pre>
     *
     * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.exchange.common.proto.OrderProto.OrderCommand> getCommandsList() {
      return commands_;
    }
    /**
     * <pre>
     * 批量订单
     * </pre>
     *
     * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.exchange.common.proto.OrderProto.OrderCommandOrBuilder> 
        getCommandsOrBuilderList() {
      return commands_;
    }
    /**
     * <pre>
     * 批量订单
     * </pre>
     *
     * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
     */
    @java.lang.Override
    public int getCommandsCount() {
      return commands_.size();
    }
    /**
     * <pre>
     * 批量订单
     * </pre>
     *
     * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
     */
    @java.lang.Override
    public com.exchange.common.proto.OrderProto.OrderCommand getCommands(int index) {
      return commands_.get(index);
    }
    /**
     * <pre>
     * 批量订单
     * </pre>
     *
     * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
     */
    @java.lang.Override
    public com.exchange.common.proto.OrderProto.OrderCommandOrBuilder getCommandsOrBuilder(
        int index) {
      return commands_.get(index);
    }

    public static final int BATCH_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object batchId_ = "";
    /**
     * <pre>
     * 批次ID
     * </pre>
     *
     * <code>string batch_id = 2;</code>
     * @return The batchId.
     */
    @java.lang.Override
    public java.lang.String getBatchId() {
      java.lang.Object ref = batchId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        batchId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 批次ID
     * </pre>
     *
     * <code>string batch_id = 2;</code>
     * @return The bytes for batchId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBatchIdBytes() {
      java.lang.Object ref = batchId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        batchId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BATCH_TIMESTAMP_FIELD_NUMBER = 3;
    private long batchTimestamp_ = 0L;
    /**
     * <pre>
     * 批次时间戳
     * </pre>
     *
     * <code>int64 batch_timestamp = 3;</code>
     * @return The batchTimestamp.
     */
    @java.lang.Override
    public long getBatchTimestamp() {
      return batchTimestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < commands_.size(); i++) {
        output.writeMessage(1, commands_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(batchId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, batchId_);
      }
      if (batchTimestamp_ != 0L) {
        output.writeInt64(3, batchTimestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < commands_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, commands_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(batchId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, batchId_);
      }
      if (batchTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, batchTimestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.exchange.common.proto.OrderProto.OrderCommandBatch)) {
        return super.equals(obj);
      }
      com.exchange.common.proto.OrderProto.OrderCommandBatch other = (com.exchange.common.proto.OrderProto.OrderCommandBatch) obj;

      if (!getCommandsList()
          .equals(other.getCommandsList())) return false;
      if (!getBatchId()
          .equals(other.getBatchId())) return false;
      if (getBatchTimestamp()
          != other.getBatchTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCommandsCount() > 0) {
        hash = (37 * hash) + COMMANDS_FIELD_NUMBER;
        hash = (53 * hash) + getCommandsList().hashCode();
      }
      hash = (37 * hash) + BATCH_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBatchId().hashCode();
      hash = (37 * hash) + BATCH_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBatchTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.exchange.common.proto.OrderProto.OrderCommandBatch parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommandBatch parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommandBatch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommandBatch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommandBatch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommandBatch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommandBatch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommandBatch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.exchange.common.proto.OrderProto.OrderCommandBatch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.exchange.common.proto.OrderProto.OrderCommandBatch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommandBatch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.exchange.common.proto.OrderProto.OrderCommandBatch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.exchange.common.proto.OrderProto.OrderCommandBatch prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * *
     * 批量订单命令（预留，用于批量下单优化）
     * </pre>
     *
     * Protobuf type {@code com.exchange.common.proto.OrderCommandBatch}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.exchange.common.proto.OrderCommandBatch)
        com.exchange.common.proto.OrderProto.OrderCommandBatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.exchange.common.proto.OrderProto.internal_static_com_exchange_common_proto_OrderCommandBatch_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.exchange.common.proto.OrderProto.internal_static_com_exchange_common_proto_OrderCommandBatch_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.exchange.common.proto.OrderProto.OrderCommandBatch.class, com.exchange.common.proto.OrderProto.OrderCommandBatch.Builder.class);
      }

      // Construct using com.exchange.common.proto.OrderProto.OrderCommandBatch.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (commandsBuilder_ == null) {
          commands_ = java.util.Collections.emptyList();
        } else {
          commands_ = null;
          commandsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        batchId_ = "";
        batchTimestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.exchange.common.proto.OrderProto.internal_static_com_exchange_common_proto_OrderCommandBatch_descriptor;
      }

      @java.lang.Override
      public com.exchange.common.proto.OrderProto.OrderCommandBatch getDefaultInstanceForType() {
        return com.exchange.common.proto.OrderProto.OrderCommandBatch.getDefaultInstance();
      }

      @java.lang.Override
      public com.exchange.common.proto.OrderProto.OrderCommandBatch build() {
        com.exchange.common.proto.OrderProto.OrderCommandBatch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.exchange.common.proto.OrderProto.OrderCommandBatch buildPartial() {
        com.exchange.common.proto.OrderProto.OrderCommandBatch result = new com.exchange.common.proto.OrderProto.OrderCommandBatch(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.exchange.common.proto.OrderProto.OrderCommandBatch result) {
        if (commandsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            commands_ = java.util.Collections.unmodifiableList(commands_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.commands_ = commands_;
        } else {
          result.commands_ = commandsBuilder_.build();
        }
      }

      private void buildPartial0(com.exchange.common.proto.OrderProto.OrderCommandBatch result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.batchId_ = batchId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.batchTimestamp_ = batchTimestamp_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.exchange.common.proto.OrderProto.OrderCommandBatch) {
          return mergeFrom((com.exchange.common.proto.OrderProto.OrderCommandBatch)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.exchange.common.proto.OrderProto.OrderCommandBatch other) {
        if (other == com.exchange.common.proto.OrderProto.OrderCommandBatch.getDefaultInstance()) return this;
        if (commandsBuilder_ == null) {
          if (!other.commands_.isEmpty()) {
            if (commands_.isEmpty()) {
              commands_ = other.commands_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCommandsIsMutable();
              commands_.addAll(other.commands_);
            }
            onChanged();
          }
        } else {
          if (!other.commands_.isEmpty()) {
            if (commandsBuilder_.isEmpty()) {
              commandsBuilder_.dispose();
              commandsBuilder_ = null;
              commands_ = other.commands_;
              bitField0_ = (bitField0_ & ~0x00000001);
              commandsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetCommandsFieldBuilder() : null;
            } else {
              commandsBuilder_.addAllMessages(other.commands_);
            }
          }
        }
        if (!other.getBatchId().isEmpty()) {
          batchId_ = other.batchId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getBatchTimestamp() != 0L) {
          setBatchTimestamp(other.getBatchTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.exchange.common.proto.OrderProto.OrderCommand m =
                    input.readMessage(
                        com.exchange.common.proto.OrderProto.OrderCommand.parser(),
                        extensionRegistry);
                if (commandsBuilder_ == null) {
                  ensureCommandsIsMutable();
                  commands_.add(m);
                } else {
                  commandsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 18: {
                batchId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                batchTimestamp_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.exchange.common.proto.OrderProto.OrderCommand> commands_ =
        java.util.Collections.emptyList();
      private void ensureCommandsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          commands_ = new java.util.ArrayList<com.exchange.common.proto.OrderProto.OrderCommand>(commands_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.exchange.common.proto.OrderProto.OrderCommand, com.exchange.common.proto.OrderProto.OrderCommand.Builder, com.exchange.common.proto.OrderProto.OrderCommandOrBuilder> commandsBuilder_;

      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public java.util.List<com.exchange.common.proto.OrderProto.OrderCommand> getCommandsList() {
        if (commandsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(commands_);
        } else {
          return commandsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public int getCommandsCount() {
        if (commandsBuilder_ == null) {
          return commands_.size();
        } else {
          return commandsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public com.exchange.common.proto.OrderProto.OrderCommand getCommands(int index) {
        if (commandsBuilder_ == null) {
          return commands_.get(index);
        } else {
          return commandsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public Builder setCommands(
          int index, com.exchange.common.proto.OrderProto.OrderCommand value) {
        if (commandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommandsIsMutable();
          commands_.set(index, value);
          onChanged();
        } else {
          commandsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public Builder setCommands(
          int index, com.exchange.common.proto.OrderProto.OrderCommand.Builder builderForValue) {
        if (commandsBuilder_ == null) {
          ensureCommandsIsMutable();
          commands_.set(index, builderForValue.build());
          onChanged();
        } else {
          commandsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public Builder addCommands(com.exchange.common.proto.OrderProto.OrderCommand value) {
        if (commandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommandsIsMutable();
          commands_.add(value);
          onChanged();
        } else {
          commandsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public Builder addCommands(
          int index, com.exchange.common.proto.OrderProto.OrderCommand value) {
        if (commandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommandsIsMutable();
          commands_.add(index, value);
          onChanged();
        } else {
          commandsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public Builder addCommands(
          com.exchange.common.proto.OrderProto.OrderCommand.Builder builderForValue) {
        if (commandsBuilder_ == null) {
          ensureCommandsIsMutable();
          commands_.add(builderForValue.build());
          onChanged();
        } else {
          commandsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public Builder addCommands(
          int index, com.exchange.common.proto.OrderProto.OrderCommand.Builder builderForValue) {
        if (commandsBuilder_ == null) {
          ensureCommandsIsMutable();
          commands_.add(index, builderForValue.build());
          onChanged();
        } else {
          commandsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public Builder addAllCommands(
          java.lang.Iterable<? extends com.exchange.common.proto.OrderProto.OrderCommand> values) {
        if (commandsBuilder_ == null) {
          ensureCommandsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, commands_);
          onChanged();
        } else {
          commandsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public Builder clearCommands() {
        if (commandsBuilder_ == null) {
          commands_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          commandsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public Builder removeCommands(int index) {
        if (commandsBuilder_ == null) {
          ensureCommandsIsMutable();
          commands_.remove(index);
          onChanged();
        } else {
          commandsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public com.exchange.common.proto.OrderProto.OrderCommand.Builder getCommandsBuilder(
          int index) {
        return internalGetCommandsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public com.exchange.common.proto.OrderProto.OrderCommandOrBuilder getCommandsOrBuilder(
          int index) {
        if (commandsBuilder_ == null) {
          return commands_.get(index);  } else {
          return commandsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public java.util.List<? extends com.exchange.common.proto.OrderProto.OrderCommandOrBuilder> 
           getCommandsOrBuilderList() {
        if (commandsBuilder_ != null) {
          return commandsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(commands_);
        }
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public com.exchange.common.proto.OrderProto.OrderCommand.Builder addCommandsBuilder() {
        return internalGetCommandsFieldBuilder().addBuilder(
            com.exchange.common.proto.OrderProto.OrderCommand.getDefaultInstance());
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public com.exchange.common.proto.OrderProto.OrderCommand.Builder addCommandsBuilder(
          int index) {
        return internalGetCommandsFieldBuilder().addBuilder(
            index, com.exchange.common.proto.OrderProto.OrderCommand.getDefaultInstance());
      }
      /**
       * <pre>
       * 批量订单
       * </pre>
       *
       * <code>repeated .com.exchange.common.proto.OrderCommand commands = 1;</code>
       */
      public java.util.List<com.exchange.common.proto.OrderProto.OrderCommand.Builder> 
           getCommandsBuilderList() {
        return internalGetCommandsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.exchange.common.proto.OrderProto.OrderCommand, com.exchange.common.proto.OrderProto.OrderCommand.Builder, com.exchange.common.proto.OrderProto.OrderCommandOrBuilder> 
          internalGetCommandsFieldBuilder() {
        if (commandsBuilder_ == null) {
          commandsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.exchange.common.proto.OrderProto.OrderCommand, com.exchange.common.proto.OrderProto.OrderCommand.Builder, com.exchange.common.proto.OrderProto.OrderCommandOrBuilder>(
                  commands_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          commands_ = null;
        }
        return commandsBuilder_;
      }

      private java.lang.Object batchId_ = "";
      /**
       * <pre>
       * 批次ID
       * </pre>
       *
       * <code>string batch_id = 2;</code>
       * @return The batchId.
       */
      public java.lang.String getBatchId() {
        java.lang.Object ref = batchId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          batchId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 批次ID
       * </pre>
       *
       * <code>string batch_id = 2;</code>
       * @return The bytes for batchId.
       */
      public com.google.protobuf.ByteString
          getBatchIdBytes() {
        java.lang.Object ref = batchId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          batchId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 批次ID
       * </pre>
       *
       * <code>string batch_id = 2;</code>
       * @param value The batchId to set.
       * @return This builder for chaining.
       */
      public Builder setBatchId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        batchId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 批次ID
       * </pre>
       *
       * <code>string batch_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchId() {
        batchId_ = getDefaultInstance().getBatchId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 批次ID
       * </pre>
       *
       * <code>string batch_id = 2;</code>
       * @param value The bytes for batchId to set.
       * @return This builder for chaining.
       */
      public Builder setBatchIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        batchId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long batchTimestamp_ ;
      /**
       * <pre>
       * 批次时间戳
       * </pre>
       *
       * <code>int64 batch_timestamp = 3;</code>
       * @return The batchTimestamp.
       */
      @java.lang.Override
      public long getBatchTimestamp() {
        return batchTimestamp_;
      }
      /**
       * <pre>
       * 批次时间戳
       * </pre>
       *
       * <code>int64 batch_timestamp = 3;</code>
       * @param value The batchTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setBatchTimestamp(long value) {

        batchTimestamp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 批次时间戳
       * </pre>
       *
       * <code>int64 batch_timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        batchTimestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.exchange.common.proto.OrderCommandBatch)
    }

    // @@protoc_insertion_point(class_scope:com.exchange.common.proto.OrderCommandBatch)
    private static final com.exchange.common.proto.OrderProto.OrderCommandBatch DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.exchange.common.proto.OrderProto.OrderCommandBatch();
    }

    public static com.exchange.common.proto.OrderProto.OrderCommandBatch getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderCommandBatch>
        PARSER = new com.google.protobuf.AbstractParser<OrderCommandBatch>() {
      @java.lang.Override
      public OrderCommandBatch parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OrderCommandBatch> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderCommandBatch> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.exchange.common.proto.OrderProto.OrderCommandBatch getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_exchange_common_proto_OrderCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_exchange_common_proto_OrderCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_exchange_common_proto_OrderCommandBatch_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_exchange_common_proto_OrderCommandBatch_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023order_command.proto\022\031com.exchange.comm" +
      "on.proto\"\304\001\n\014OrderCommand\022\020\n\010order_id\030\001 " +
      "\001(\003\022\017\n\007user_id\030\002 \001(\003\022\016\n\006symbol\030\003 \001(\t\022\014\n\004" +
      "side\030\004 \001(\t\022\022\n\norder_type\030\005 \001(\t\022\r\n\005price\030" +
      "\006 \001(\t\022\020\n\010quantity\030\007 \001(\t\022\022\n\nevent_type\030\010 " +
      "\001(\t\022\021\n\ttimestamp\030\t \001(\003\022\027\n\017client_order_i" +
      "d\030\n \001(\t\"y\n\021OrderCommandBatch\0229\n\010commands" +
      "\030\001 \003(\0132\'.com.exchange.common.proto.Order" +
      "Command\022\020\n\010batch_id\030\002 \001(\t\022\027\n\017batch_times" +
      "tamp\030\003 \001(\003B)\n\031com.exchange.common.protoB" +
      "\nOrderProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_exchange_common_proto_OrderCommand_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_com_exchange_common_proto_OrderCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_exchange_common_proto_OrderCommand_descriptor,
        new java.lang.String[] { "OrderId", "UserId", "Symbol", "Side", "OrderType", "Price", "Quantity", "EventType", "Timestamp", "ClientOrderId", });
    internal_static_com_exchange_common_proto_OrderCommandBatch_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_com_exchange_common_proto_OrderCommandBatch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_exchange_common_proto_OrderCommandBatch_descriptor,
        new java.lang.String[] { "Commands", "BatchId", "BatchTimestamp", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
