server:
  port: ${SERVER_PORT:8099}

spring:
  application:
    name: mark-price-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:nacos:${spring.application.name}-${spring.profiles.active}.yml

  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: DEFAULT_GROUP
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        file-extension: yml
        namespace: ${NACOS_NAMESPACE:}
        group: DEFAULT_GROUP
        import-check:
          enabled: false

# Logging配置
logging:
  level:
    com.exchange.mark-price-core: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/mark-price-core.log
